//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Member
{


    public partial class CourseDetails
    {

        /// <summary>
        /// pnlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCourse;

        /// <summary>
        /// litCourseName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseName;

        /// <summary>
        /// litTechStack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTechStack;

        /// <summary>
        /// litDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDescription;

        /// <summary>
        /// barProgress control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barProgress;

        /// <summary>
        /// rptModules control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptModules;

        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
    }
}