//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Account
{

    /// <summary>
    /// Declares the controls declared in ForgotPassword.aspx so the code-behind
    /// can refer to them by name.
    /// </summary>
    public partial class ForgotPassword
    {

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnSendLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSendLink;
    }
}
