//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Account
{

    /// <summary>
    /// Declares the controls declared in ResetPassword.aspx so the code-behind
    /// can refer to them by name.
    /// </summary>
    public partial class ResetPassword
    {

        /// <summary>
        /// pnlInvalidLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlInvalidLink;

        /// <summary>
        /// lblInvalidLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblInvalidLink;

        /// <summary>
        /// pnlResetForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResetForm;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;
    }
}
