//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class AdminDashboard
    {

        /// <summary>
        /// litPublishedCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPublishedCourses;

        /// <summary>
        /// litActiveStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActiveStudents;

        /// <summary>
        /// litAttemptsWeek control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAttemptsWeek;

        /// <summary>
        /// litAvgPassRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvgPassRate;

        /// <summary>
        /// grdRecent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdRecent;

        /// <summary>
        /// grdStacks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdStacks;
    }
}