//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class ManageQuestions
    {

        /// <summary>
        /// ddlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlQuiz;

        /// <summary>
        /// pnlWorkspace control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlWorkspace;

        /// <summary>
        /// grdQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdQuestions;

        /// <summary>
        /// lblEditorHeading control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblEditorHeading;

        /// <summary>
        /// hidQuestionId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidQuestionId;

        /// <summary>
        /// txtQuestionText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuestionText;

        /// <summary>
        /// txtMarks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarks;

        /// <summary>
        /// rptAnswerRows control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAnswerRows;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
    }
}