//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class ManageCourses
    {

        /// <summary>
        /// pnlEditor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEditor;

        /// <summary>
        /// lblEditorHeading control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblEditorHeading;

        /// <summary>
        /// hidCourseId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidCourseId;

        /// <summary>
        /// txtCourseName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCourseName;

        /// <summary>
        /// ddlTechStack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTechStack;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccess;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>
        /// grdCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdCourses;
    }
}