//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class ManageQuizzes
    {

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// ddlModule control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlModule;

        /// <summary>
        /// pnlWorkspace control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlWorkspace;

        /// <summary>
        /// grdQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdQuizzes;

        /// <summary>
        /// litHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeading;

        /// <summary>
        /// pnlEditor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEditor;

        /// <summary>
        /// hidQuizId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidQuizId;

        /// <summary>
        /// txtQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;

        /// <summary>
        /// txtPassMark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassMark;

        /// <summary>
        /// txtDurationMinutes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDurationMinutes;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnSaveQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveQuiz;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>
        /// btnDeleteQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeleteQuiz;

        /// <summary>
        /// lnkManageQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkManageQuestions;
    }
}