//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class ManageModules
    {

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// pnlWorkspace control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlWorkspace;

        /// <summary>
        /// txtModuleTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtModuleTitle;

        /// <summary>
        /// btnAddModule control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddModule;

        /// <summary>
        /// pnlRename control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRename;

        /// <summary>
        /// hidRenameModuleId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidRenameModuleId;

        /// <summary>
        /// txtRenameTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRenameTitle;

        /// <summary>
        /// btnSaveRename control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveRename;

        /// <summary>
        /// btnCancelRename control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelRename;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// grdModules control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdModules;
    }
}