//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class ManageLessons
    {

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// ddlModule control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlModule;

        /// <summary>
        /// pnlWorkspace control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlWorkspace;

        /// <summary>
        /// grdLessons control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdLessons;

        /// <summary>
        /// lnkManageQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkManageQuizzes;

        /// <summary>
        /// lblEditorHeading control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblEditorHeading;

        /// <summary>
        /// hidLessonId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidLessonId;

        /// <summary>
        /// txtLessonTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLessonTitle;

        /// <summary>
        /// txtContentHtml control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContentHtml;

        /// <summary>
        /// txtVideoUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;

        /// <summary>
        /// fupNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fupNotes;

        /// <summary>
        /// lblCurrentNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentNotes;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSuccess;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
    }
}