//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Admin
{


    public partial class Reports
    {

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// grdResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdResults;

        /// <summary>
        /// pnlProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProgress;

        /// <summary>
        /// grdProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdProgress;
    }
}