//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web
{


    public partial class Register
    {

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// btnRegister control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}