//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web
{


    public partial class SiteMaster
    {

        /// <summary>
        /// pnlAnonymous control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAnonymous;

        /// <summary>
        /// pnlStudent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlStudent;

        /// <summary>
        /// pnlAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdmin;

        /// <summary>
        /// pnlAuthenticated control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAuthenticated;

        /// <summary>
        /// litUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUser;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}