//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Masterpages
{


    public partial class AdminMaster
    {

        /// <summary>
        /// litAdminName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAdminName;

        /// <summary>
        /// btnAdminLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAdminLogout;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
