//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Student
{


    public partial class CourseCatalog
    {

        /// <summary>
        /// ddlTechStackFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTechStackFilter;

        /// <summary>
        /// rptCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}