//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Student
{


    public partial class LessonViewer
    {

        /// <summary>
        /// pnlLesson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLesson;

        /// <summary>
        /// lnkBack control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBack;

        /// <summary>
        /// litLessonTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLessonTitle;

        /// <summary>
        /// litContentHtml control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litContentHtml;

        /// <summary>
        /// pnlVideo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVideo;

        /// <summary>
        /// frmVideo control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl frmVideo;

        /// <summary>
        /// hlDownloadNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink hlDownloadNotes;

        /// <summary>
        /// btnMarkComplete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnMarkComplete;

        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
    }
}