//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStackLearningHub.Web.Student
{


    public partial class QuizPage
    {

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// litQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmitQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;

        /// <summary>
        /// pnlResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>
        /// litOutcome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label litOutcome;

        /// <summary>
        /// litScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litScore;

        /// <summary>
        /// litPassMark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPassMark;

        /// <summary>
        /// lnkBackToCourse control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBackToCourse;

        /// <summary>
        /// pnlRetake control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRetake;

        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
    }
}